---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      - name: "Build"
        shell: bash
        run: |
          sudo ./build.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "auto-build"
          prerelease: false
          files: |
            spdk/LICENSE
            spdk/build/bin/nvmf_tgt
            