---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Reset permissions"
        run: |
          export CURRENT_USER="`whoami`"
          sudo rm -rf *
          sudo rm -rf .git*
          sudo -E chown -R $CURRENT_USER:$CURRENT_USER .
    
      - uses: actions/checkout@v2

      - name: "Run pre-build script"
        run: |
          ./build-initial.sh

      - name: "Build nvmf-tgt"
        run: |
          ./build.sh
        
      - name: "Build deb package"
        run: |
          ./build-deb.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Release NVMe-oF Target ${{ env.SPDK_VERSION_MAJOR }}.${{ env.SPDK_VERSION_MINOR }}.${{ env.SPDK_VERSION_PATCH }}-${{ env.SPDK_VERSION_UNIXTIME }}v${{ env.SPDK_VERSION_HASH }}"
          automatic_release_tag: "v${{ env.SPDK_VERSION_MAJOR }}.${{ env.SPDK_VERSION_MINOR }}.${{ env.SPDK_VERSION_PATCH }}-${{ env.SPDK_VERSION_UNIXTIME }}v${{ env.SPDK_VERSION_HASH }}-ubuntu"
          prerelease: false
          files: |
            *.deb
            